# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming_voice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'streaming_voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15streaming_voice.proto\x12\x0fstreaming_voice\"!\n\x0cVoiceRequest\x12\x11\n\tbyte_buff\x18\x01 \x01(\x0c\"Q\n\tTextReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\'\n\x06result\x18\x03 \x01(\x0b\x32\x17.streaming_voice.Result\"H\n\x06Result\x12\r\n\x05\x66inal\x18\x01 \x01(\x08\x12/\n\nhypotheses\x18\x02 \x03(\x0b\x32\x1b.streaming_voice.Hypothesis\"4\n\nHypothesis\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32Y\n\x0bStreamVoice\x12J\n\tSendVoice\x12\x1d.streaming_voice.VoiceRequest\x1a\x1a.streaming_voice.TextReply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOICEREQUEST']._serialized_start=42
  _globals['_VOICEREQUEST']._serialized_end=75
  _globals['_TEXTREPLY']._serialized_start=77
  _globals['_TEXTREPLY']._serialized_end=158
  _globals['_RESULT']._serialized_start=160
  _globals['_RESULT']._serialized_end=232
  _globals['_HYPOTHESIS']._serialized_start=234
  _globals['_HYPOTHESIS']._serialized_end=286
  _globals['_STREAMVOICE']._serialized_start=288
  _globals['_STREAMVOICE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
